AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys an ECS cluster

Parameters:
  VpcId:
    Description: VPC where the ECS tasks and ALB will run
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Description: List of subnets for ALB
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: FargateCluster
  
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecs:StartTelemetrySession
                  - ecs:Poll
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs: 
  EcsCluster:
    Description: A reference to the ECS cluster
    Value: !Ref ECSCluster

  EcsTaskExecutionRoleArn:
    Description: The ECS Execution Role.
    Value: !GetAtt EcsTaskExecutionRole.Arn