AWSTemplateFormatVersion: "2010-09-09"
Description: >
  VPC with public and private subnets in 2 AZs; IGW; NAT Gateways; 
  RDS PostgresDB;

Parameters:
  Env:
    Type: String
    Default: "dev"
    Description: Environment
    AllowedValues: ['dev', 'qc', 'uat', 'staging', 'prod']
  
  ProjectName:
    Type: String
    Description: Project Name
    Default: nestjsmicrosvc
  
  LogLevel:
    Type: String
    Description: Log level for the services
    Default: 'verbose'
    AllowedValues: ['error', 'warn', 'info', 'http', 'verbose', 'debug', 'silly']

  NestedStacksBaseS3Uri:
    Type: String
    Description: The S3 bucket that holds the nested stack (without trailing slash '/').
    Default: https://cf-templates-mynest-app.s3.amazonaws.com

  # EC2KeyName: 
  #   Description: The EC2 Key Pair to allow SSH access to the instances
  #   Type: AWS::EC2::KeyPair::KeyName
  #   ConstraintDescription: Must be the name of an existing EC2 KeyPair

  # BastionHostAdminPassword:
  #   Type: String
  #   NoEcho: true
  #   Description: The admin password for Bastion Host

  RdsPostgresDbPassword:
    Type: String
    NoEcho: true
    Description: The root user password for RDS PostgreSQL instance

  # SecretName:
  #   Description: The name of the AWS Secret that holds the values for sensitive Env vars.    
  #   Type: String
  #   Default: nestapp-dev-api-secrets

  # SecretsVersion:
  #   Description: Version of secrets in AWS Secrets Manager. Use this to force-update secrets.
  #   Type: String
  #   Default: "20231107T0300PM"

  # AcmCertificateId:
  #   Description: SSL Certificate Id from ACM
  #   Type: String

  VpcCIDR:
    Type: String
    Description: 'Non overlapping VPC Cidr IP'
    Default: '10.8.0.0/16'
  PublicSubnet1CIDR:
    Type: String
    Description: 'Public subnet1 CIDR'
    Default: '10.8.0.0/24'
  PublicSubnet2CIDR:
    Type: String
    Description: 'Public subnet2 CIDR'
    Default: '10.8.1.0/24'
  PrivateSubnet1CIDR:
    Type: String
    Description: 'Private subnet1 CIDR'
    Default: '10.8.2.0/24'
  PrivateSubnet2CIDR:
    Type: String
    Description: 'Private subnet2 CIDR'
    Default: '10.8.3.0/24'

Conditions: 
  IsProduction: !Equals ['prod', !Ref Env] 

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${NestedStacksBaseS3Uri}/${Env}/vpc.yaml
      Parameters:        
        Env: !Ref Env
        VpcCIDR: !Ref VpcCIDR 
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  EcrStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${NestedStacksBaseS3Uri}/${Env}/ecr.yaml
      Parameters:        
        ProjectName: !Ref ProjectName
        Env: !Ref Env
  
  EcsClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${NestedStacksBaseS3Uri}/${Env}/ecs-cluster.yaml
  
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${NestedStacksBaseS3Uri}/${Env}/load-balancer.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        Env: !Ref Env
        VpcId: !GetAtt VpcStack.Outputs.Vpc
        PublicSubnets: !GetAtt VpcStack.Outputs.PublicSubnets
  
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${NestedStacksBaseS3Uri}/${Env}/db-rds.yaml
      Parameters:        
        ProjectName: !Ref ProjectName
        Env: !Ref Env
        VpcId: !GetAtt VpcStack.Outputs.Vpc
        VpcCIDR: !Ref VpcCIDR
        PrivateSubnets: !GetAtt VpcStack.Outputs.PrivateSubnets
        RdsPostgresDbUsername: testuser
        RdsPostgresDbPassword: !Ref RdsPostgresDbPassword
              
  #  ### !!! Ensure that ECR has an image before creating the API service !!! ###
  ApiServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${NestedStacksBaseS3Uri}/${Env}/api-service.yaml
      Parameters:        
        ProjectName: !Ref ProjectName
        Env: !Ref Env
        VpcId: !GetAtt VpcStack.Outputs.Vpc
        SubnetIds: !GetAtt VpcStack.Outputs.PrivateSubnets
        # EcsAlbListener: !GetAtt LoadBalancerStack.Outputs.Listener
        EcsAlbListenerHTTP: !GetAtt LoadBalancerStack.Outputs.ListenerHTTP
        AlbListenerRulePriority: "211"
        EcsTaskExecutionRoleArn: !GetAtt EcsClusterStack.Outputs.EcsTaskExecutionRoleArn
        EcsCluster: !GetAtt EcsClusterStack.Outputs.EcsCluster        
        ServiceContainerPort: 3000
        PostgresDbConStr: !Join [ "", [ !GetAtt DatabaseStack.Outputs.PostgresConnectionString, !Sub '${ProjectName}-${Env}' ] ]

Outputs:
  
  # BastionHost:
  #   Description: Bastion Host URL
  #   Value: !Join ["", [ "Administrator:", !Ref BastionHostAdminPassword,"@", !GetAtt BastionServerStack.Outputs.BastionHost]]

  DbConnectionStr:
    Description: Database Connection String
    Value: !GetAtt DatabaseStack.Outputs.PostgresConnectionString

  VpcDetails:
    Description: Vpc details
    Value: !GetAtt VpcStack.Outputs.Vpc
 