---
- ParameterKey: AcmCertificateId
  UsePreviousValue: true
- ParameterKey: BastionHostAdminPassword
  UsePreviousValue: true
- ParameterKey: EC2KeyName
  UsePreviousValue: true
- ParameterKey: Env
  ParameterValue: dev
- ParameterKey: LogLevel
  ParameterValue: verbose
- ParameterKey: NestedStacksBaseS3Uri
  ParameterValue: https://nestapp-cf-templates.s3.amazonaws.com/$(ENV)
- ParameterKey: ProjectName
  ParameterValue: nestapp
- ParameterKey: RdsPostgresDbPassword
  UsePreviousValue: true
- ParameterKey: RestrictedIp
  ParameterValue: 103.135.95.18
- ParameterKey: SecretName
  ParameterValue: nestapp-$(ENV)-api-secrets
- ParameterKey: SecretsVersion
  ParameterValue: $(SECRETVERSION)
- ParameterKey: VpcCidrIp
  UsePreviousValue: true
